name: React CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: Deploy to github pages
        run: |
          yarn deploy
